/**
 * Devises ISO 4217 en circulation, avec leur nom en français. Sert à préremplir la table `currencies`
 * (convex/currencies.ts:seedAllKnown) pour que l'admin n'ait plus à ajouter les devises une par une -
 * il n'a qu'à les activer/désactiver ou en ajouter une manquante si besoin.
 *
 * Vérifié le 2026-09-30 contre les changements de code ISO 4217 récents (source: SIX Group / Wikipedia) :
 * ANG (florin antillais) retiré le 31/03/2025, remplacé par XCG (florin caribéen) ; BGN (lev bulgare)
 * retiré au 01/01/2026, la Bulgarie utilisant désormais EUR ; ZWL (dollar zimbabwéen) retiré le
 * 01/09/2024, remplacé par ZWG (Zimbabwe Gold / ZiG).
 */
export const KNOWN_CURRENCIES: Record<string, string> = {
  AED: "Dirham des Émirats arabes unis",
  AFN: "Afghani afghan",
  ALL: "Lek albanais",
  AMD: "Dram arménien",
  AOA: "Kwanza angolais",
  ARS: "Peso argentin",
  AUD: "Dollar australien",
  AWG: "Florin arubais",
  AZN: "Manat azerbaïdjanais",
  BAM: "Mark convertible bosniaque",
  BBD: "Dollar barbadien",
  BDT: "Taka bangladais",
  BHD: "Dinar bahreïni",
  BIF: "Franc burundais",
  BMD: "Dollar bermudien",
  BND: "Dollar de Brunei",
  BOB: "Boliviano bolivien",
  BRL: "Real brésilien",
  BSD: "Dollar bahaméen",
  BTN: "Ngultrum bhoutanais",
  BWP: "Pula botswanais",
  BYN: "Rouble biélorusse",
  BZD: "Dollar bélizien",
  CAD: "Dollar canadien",
  CDF: "Franc congolais",
  CHF: "Franc suisse",
  CLP: "Peso chilien",
  CNY: "Yuan renminbi chinois",
  COP: "Peso colombien",
  CRC: "Colón costaricien",
  CUP: "Peso cubain",
  CVE: "Escudo cap-verdien",
  CZK: "Couronne tchèque",
  DJF: "Franc djiboutien",
  DKK: "Couronne danoise",
  DOP: "Peso dominicain",
  DZD: "Dinar algérien",
  EGP: "Livre égyptienne",
  ERN: "Nakfa érythréen",
  ETB: "Birr éthiopien",
  EUR: "Euro",
  FJD: "Dollar fidjien",
  FKP: "Livre des îles Malouines",
  GBP: "Livre sterling",
  GEL: "Lari géorgien",
  GHS: "Cedi ghanéen",
  GIP: "Livre de Gibraltar",
  GMD: "Dalasi gambien",
  GNF: "Franc guinéen",
  GTQ: "Quetzal guatémaltèque",
  GYD: "Dollar guyanien",
  HKD: "Dollar de Hong Kong",
  HNL: "Lempira hondurien",
  HTG: "Gourde haïtienne",
  HUF: "Forint hongrois",
  IDR: "Roupie indonésienne",
  ILS: "Nouveau shekel israélien",
  INR: "Roupie indienne",
  IQD: "Dinar irakien",
  IRR: "Rial iranien",
  ISK: "Couronne islandaise",
  JMD: "Dollar jamaïcain",
  JOD: "Dinar jordanien",
  JPY: "Yen japonais",
  KES: "Shilling kényan",
  KGS: "Som kirghize",
  KHR: "Riel cambodgien",
  KMF: "Franc comorien",
  KPW: "Won nord-coréen",
  KRW: "Won sud-coréen",
  KWD: "Dinar koweïtien",
  KYD: "Dollar des îles Caïmans",
  KZT: "Tenge kazakh",
  LAK: "Kip laotien",
  LBP: "Livre libanaise",
  LKR: "Roupie srilankaise",
  LRD: "Dollar libérien",
  LSL: "Loti lesothan",
  LYD: "Dinar libyen",
  MAD: "Dirham marocain",
  MDL: "Leu moldave",
  MGA: "Ariary malgache",
  MKD: "Denar macédonien",
  MMK: "Kyat birman",
  MNT: "Tugrik mongol",
  MOP: "Pataca macanaise",
  MRU: "Ouguiya mauritanien",
  MUR: "Roupie mauricienne",
  MVR: "Rufiyaa maldivienne",
  MWK: "Kwacha malawite",
  MXN: "Peso mexicain",
  MYR: "Ringgit malaisien",
  MZN: "Metical mozambicain",
  NAD: "Dollar namibien",
  NGN: "Naira nigérian",
  NIO: "Córdoba nicaraguayen",
  NOK: "Couronne norvégienne",
  NPR: "Roupie népalaise",
  NZD: "Dollar néo-zélandais",
  OMR: "Rial omanais",
  PAB: "Balboa panaméen",
  PEN: "Sol péruvien",
  PGK: "Kina papouan-néo-guinéen",
  PHP: "Peso philippin",
  PKR: "Roupie pakistanaise",
  PLN: "Zloty polonais",
  PYG: "Guarani paraguayen",
  QAR: "Riyal qatari",
  RON: "Leu roumain",
  RSD: "Dinar serbe",
  RUB: "Rouble russe",
  RWF: "Franc rwandais",
  SAR: "Riyal saoudien",
  SBD: "Dollar des îles Salomon",
  SCR: "Roupie seychelloise",
  SDG: "Livre soudanaise",
  SEK: "Couronne suédoise",
  SGD: "Dollar de Singapour",
  SHP: "Livre de Sainte-Hélène",
  SLE: "Leone sierra-léonais",
  SOS: "Shilling somalien",
  SRD: "Dollar surinamais",
  SSP: "Livre sud-soudanaise",
  STN: "Dobra santoméen",
  SYP: "Livre syrienne",
  SZL: "Lilangeni swazi",
  THB: "Baht thaïlandais",
  TJS: "Somoni tadjik",
  TMT: "Manat turkmène",
  TND: "Dinar tunisien",
  TOP: "Pa'anga tongien",
  TRY: "Livre turque",
  TTD: "Dollar de Trinité-et-Tobago",
  TWD: "Nouveau dollar taïwanais",
  TZS: "Shilling tanzanien",
  UAH: "Hryvnia ukrainienne",
  UGX: "Shilling ougandais",
  USD: "Dollar américain",
  UYU: "Peso uruguayen",
  UZS: "Sum ouzbek",
  VES: "Bolívar vénézuélien",
  VND: "Dong vietnamien",
  VUV: "Vatu vanuatuan",
  WST: "Tala samoan",
  XAF: "Franc CFA (CEMAC)",
  XCD: "Dollar des Caraïbes orientales",
  XCG: "Florin caribéen (Curaçao, Saint-Martin néerlandais)",
  XOF: "Franc CFA (UEMOA)",
  XPF: "Franc CFP",
  YER: "Rial yéménite",
  ZAR: "Rand sud-africain",
  ZMW: "Kwacha zambien",
  ZWG: "Zimbabwe Gold (ZiG)",
};
